### ISSUE TITLE
IRI doubt in Object ID with two # chars

### ISSUE THREAD

**Issue by nphoenix** [adlnet/xapi-jqm#80]
I am using the course quiz sample with LearningLocker 1.5. The activity object ID contains two # characters and  this is interpreted as an invalid IRI by LearningLocker. 

Example object id: http://adlnet.gov/xapi/samples/xapi-jqm/course/chapters/05-quiz#quiz#q2

The hard coded moduleID label can be changed or the  concatenated delimiter for the questionID

**Comment by fugu13** [comment]
Learning Locker is correct. Just saw a client testing using this example. The fragment may contain:

> fragment    = *( pchar / "/" / "?" )

And a pchar may be:

> pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

A # is not in unreserved:

> unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

, pct-encoded is a percent sign followed by two hex characters, and sub-delims lack it as well:

> sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

**Comment by ljwolford** [comment]
closed in update
